### ISSUE TITLE
Docker build fails because of dependancies

### ISSUE THREAD

**Issue by evilalmus** [rzmk/discord-palm-bot#12]
## 🔍 Describe the bug

Docker build fails because of dependencies
Failed module: aiohttp

## 🔄 To Reproduce

Follow the build instructions from the README:
Failed at step: docker `build -t discord-llm-bot .`

## Resolution

I am not sure where the conflict exists but editing `Dockerfile` from `FROM python:latest` to `FROM python:3.10` seems to have resolved the issue.

**Comment by rzmk** [comment]
Thanks for the report @evilalmus!

Yep I just tried it and also got the same dependency issue. I developed this with Python 3.10.6 so I'll set `FROM python:3.10` as you've mentioned as the default for the Dockerfile to ensure a stable version exists since it works for me too.

Higher versions may be used by updating the packages in `requirements.txt`, though I haven't tested them.
